[package]
name = "headr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1"

[dev-dependencies]
assert_cmd = "2"
predicates = "3.1"
rand = "0.8.5"
pretty_assertions = "1.4.0"
